- hosts: all
  become: true
  pre_tasks:


  - name: install updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
        - Cinder
        - Horizon
        - Neutron
